# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number. %run initialise.py


In [2]:
NICKNAME = "skkali"

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/79833/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/79833/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/79833/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/79833/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/79833/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/79833/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/79833/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/79833/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
print(np.zeros(10)) #создает массив заполненный нулями

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
print(np.size(np.arange(10))) #число элементов в массиве
print(np.arange(10).size * np.arange(10).itemsize) #Размер памяти занимаемый вектором в байтах

10
40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
a = np.zeros(10) #создаем массив заполненный нулями
a[4] = 1 #меняем пятый элемент на единицу
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
print(np.arange(10,50)[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
#способ из дз с numpy
def matrix(): 
    m = np.arange(9).reshape(3,3)
    return m
matrix()
#а можно так
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
print(np.nonzero(np.array([1,2,0,0,4,0]))) #Возвращает индексы элементов, которые не равны нулю

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
print(np.random.randint(low=0 , high= 3,size=(3,3,3))) #Возвращает числа в заданном интервале
print(np.random.random((3,3,3))) #Возвращает числа в интервале от 0 до 1

[[[2 2 0]
  [0 1 0]
  [1 0 0]]

 [[0 2 0]
  [2 2 1]
  [1 1 1]]

 [[2 0 0]
  [2 0 1]
  [0 1 2]]]
[[[0.06764684 0.86336914 0.53871248]
  [0.57641046 0.83721568 0.44467975]
  [0.79039013 0.63536088 0.17415473]]

 [[0.42667748 0.28993826 0.80461849]
  [0.32771884 0.46814763 0.75406535]
  [0.3834865  0.92025481 0.88155926]]

 [[0.82840552 0.56416975 0.94570264]
  [0.29416794 0.58097013 0.85630522]
  [0.36545984 0.21505238 0.52374505]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
print(np.random.random((10,10)))
print("Максимум: ", np.random.random((10,10)).max())
print('Минимум: ', np.random.random((10,10)).min())

[[0.73191302 0.29056196 0.27484343 0.91607298 0.89690719 0.65370866
  0.81476757 0.02802719 0.43437749 0.86962928]
 [0.32848847 0.05666129 0.52568604 0.0696494  0.23341088 0.68790481
  0.18857368 0.69212986 0.3597635  0.385817  ]
 [0.07281373 0.43222754 0.49382093 0.07731627 0.67357841 0.66022118
  0.54247304 0.71991391 0.86919745 0.82762307]
 [0.72397659 0.09629854 0.1338736  0.67437802 0.90877256 0.02629287
  0.25823931 0.45047275 0.6751413  0.34201083]
 [0.10106401 0.80074281 0.85308364 0.31714786 0.67756155 0.02868939
  0.12092606 0.60144096 0.22364578 0.16503547]
 [0.27516936 0.51895154 0.49093777 0.60277864 0.23459954 0.31754153
  0.75892815 0.76868253 0.40083943 0.70329384]
 [0.12052374 0.35527915 0.23402281 0.57650522 0.67160162 0.29173061
  0.29482238 0.33367301 0.20282581 0.21161382]
 [0.95014333 0.19448    0.2438888  0.64778062 0.43267681 0.32546673
  0.93069423 0.51411018 0.47157109 0.37583552]
 [0.12259644 0.83764849 0.77668574 0.54043773 0.42864267 0.65531248
  0.63029048

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
print(np.random.random(30))
print(np.random.random(30).mean()) #Возвращает среднее значение

[0.34986176 0.38817612 0.31147562 0.49023134 0.84313467 0.26176992
 0.34376998 0.6627274  0.39510705 0.5208173  0.36590804 0.5462404
 0.62357819 0.31305072 0.48935368 0.06093971 0.97189488 0.04233049
 0.30446994 0.86716109 0.36496392 0.84571613 0.10697409 0.10403183
 0.88955357 0.91147514 0.8773694  0.07070945 0.40400697 0.73811087]
0.5816192774189558


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
a = np.ones((10,10))
a[1:-1, 1:-1] = 0 #Меняем внутренние значения на 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
a = np.ones((5,5)) #для примера возьмем массив 5х5
a = np.pad(a, pad_width=1, mode='constant', constant_values=0) #Заполняет края массива нужным количеством нужных объектов
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
print(np.diag(np.arange(1,5),k=-1)) #создаем массив нужный на диагональ, затем распределяем его, K-шаг смещение по диагонали

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
#способ из дз с numpy
def checkerboard(w, b):
    m = np.tile(np.array([[0,1],[1,0]]), (4,4))
    return m
print(checkerboard(1, 0))
#а можно так
a = np.zeros((8,8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
#т.к. счет начинается с 0 сотый элемент -> 99
print(np.unravel_index(99, (6,7,8))) #Преобразуем плоский индекс вектора или массив плоских индексов в кортеж массивов координат

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
#опять же можно сделать как в дз с numpy
def checkerboard(w, b):
    m = np.tile(np.array([[0,1],[1,0]]), (4,4))
    return m
print(checkerboard(1, 0))
#а можно так
a = np.array([[0,1], [1,0]]) #создаем одну ячейку
a = np.tile(a, (4,4)) #заполняем созданными ячейками всё поле
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
a = (np.random.random((5,5)) - np.random.random((5,5)).min()) / (np.random.random((5,5)).max() - np.random.random((5,5)).min())
print(a)

[[ 0.85842515  0.23997168  0.03160095  0.62011247  0.87096324]
 [ 1.03497927  0.06627261 -0.00901798  0.42217679  0.61614699]
 [ 0.63397263  0.96143987  0.33907972  0.89350523  0.24673359]
 [ 0.51417888  0.97257815  0.48612993  0.43864219  0.01105585]
 [ 0.08180352  0.33964076  0.76716544  0.19127492  0.70561092]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
print(np.dtype([('r', np.ubyte),('g', np.ubyte),('b', np.ubyte),('a', np.ubyte)]))

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
print(np.matmul(np.random.random((5,3)),np.random.random((3,2)))) #матричное произведение двух массивов

[[1.2589243  0.96059988]
 [0.52695529 0.61901775]
 [0.79490443 1.37078485]
 [0.86008915 1.04247702]
 [0.44940643 0.67953408]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
a = np.arange(11)
a[(3<a) & (a <8)] *= -1
print(a)
#можно по старинке через цикл
a = np.arange(11)
for i in range (len(a)):
    if a[i] > 3 and a[i] < 8:
        a[i] = - a[i]
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
Z=np.arange(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
try:
    print(Z<Z>Z) # при обычном запуске дает ошибку
except Exception as e:
    print('Z<Z>Z так нельзя - бан')

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Z<Z>Z так нельзя - бан


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\79833\AppData\Local\Temp\ipykernel_22176\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\79833\AppData\Local\Temp\ipykernel_22176\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [32]:
a = np.random.uniform(-10, +10, 10)
print(a)
print(np.copysign(np.ceil(np.abs(a)), a))

[ 5.65985112 -8.36172343  6.45790928 -7.31948223  2.34273074  5.36437112
  9.37921939  4.73652469 -7.24509639  2.81430033]
[ 6. -9.  7. -8.  3.  6. 10.  5. -8.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [34]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(a1)
print(a2)
print(np.intersect1d(a1,a2))

[0 0 0 5 9 9 8 2 5 5]
[8 4 9 6 9 4 5 3 2 5]
[2 5 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [35]:
defaults = np.seterr(all = 'ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [36]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [39]:
s = np.datetime64('today')
y = np.datetime64('today') - np.timedelta64(1)
t = np.datetime64('today') + np.timedelta64(1)
print('Вчера: ',y)
print('Сегодня: ',s)
print('Завтра ',t)

Вчера:  2022-12-19
Сегодня:  2022-12-20
Завтра  2022-12-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [40]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [47]:
#чтобы оценить результат возьмем такие массивы
A = np.ones(5) * 1 
B = np.ones(5) * 2
print(A)
print(B)
np.add(A,B, out=B)
np.divide(A,2, out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)
print(A)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
[-1.5 -1.5 -1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [50]:
a = np.random.uniform(1,10,10)
print(a - a%1) #через %
print(np.floor(a)) #через floor
print(np.ceil(a)-1) #через ceil
print(a.astype(int)) #через astype
print(np.trunc(a)) #через trunc

[8. 4. 7. 6. 6. 4. 1. 6. 2. 6.]
[8. 4. 7. 6. 6. 4. 1. 6. 2. 6.]
[8. 4. 7. 6. 6. 4. 1. 6. 2. 6.]
[8 4 7 6 6 4 1 6 2 6]
[8. 4. 7. 6. 6. 4. 1. 6. 2. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [51]:
a = np.zeros((5,5)) 
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [53]:
def generator():
    for x in range(10):
        yield x
print(np.fromiter(generator(), dtype=float, count=-1))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [55]:
print(np.linspace(0,1,11,endpoint=False)[1:]) #Возвращает равномерно распределенные числа в интервале
#endpoint=False конечная точка интервала может быть исключена

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [57]:
print(np.sort(np.random.random(10)))

[0.0491199  0.14041643 0.26345926 0.30628735 0.48868634 0.53724664
 0.61261606 0.72179131 0.8256931  0.8800442 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [58]:
print(np.add.reduce(np.arange(10)))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [60]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(a)
print(b)
print(np.allclose(a,b))
print(np.array_equal(a,b))

[7 4 6 3 6 1 8 1 8 9]
[1 1 9 4 2 1 6 2 0 5]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [64]:
a = np.ones(5, dtype=int)
a.flags.writeable=False
print(a)
try:
    a[1] = 0   
except Exception as e:
    print('a[1] = 0 так нельзя - бан')

[1 1 1 1 1]
a[1] = 0 так нельзя - бан


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [66]:
a = np.random.random((10,2))
print(a)

x,y = a[:,0], a[:,1]
print(x)
print(y)

A = np.sqrt(x**2 + y** 2)
B = np.arctan2(y,x)
print(A)
print(B)

[[0.23723285 0.66499285]
 [0.36048119 0.33575579]
 [0.03939607 0.23898473]
 [0.71658678 0.2446099 ]
 [0.15974012 0.96813578]
 [0.40277939 0.03417611]
 [0.01060101 0.64609025]
 [0.14661629 0.43466063]
 [0.77013782 0.9205544 ]
 [0.9670992  0.27617781]]
[0.23723285 0.36048119 0.03939607 0.71658678 0.15974012 0.40277939
 0.01060101 0.14661629 0.77013782 0.9670992 ]
[0.66499285 0.33575579 0.23898473 0.2446099  0.96813578 0.03417611
 0.64609025 0.43466063 0.9205544  0.27617781]
[0.70604172 0.49262424 0.24221014 0.75718599 0.98122566 0.40422672
 0.64617722 0.45872235 1.20022192 1.00576093]
[1.22812532 0.74990017 1.40741804 0.32895187 1.40727201 0.08464794
 1.55438985 1.24546917 0.87413199 0.2781694 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [68]:
a = np.random.randint(1,10, 10)
print(a)
a[a.argmax()] = 0
print(a)

[1 3 4 3 8 2 3 5 3 5]
[1 3 4 3 0 2 3 5 3 5]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [72]:
a = np.zeros((5,5), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [75]:
X = np.arange(5)
Y = X + 0.5
C = 1 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [77]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype}: min={info.min}, max={info.max}")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype}: min={info.min}, max={info.max}")

<class 'numpy.int8'>: min=-128, max=127
<class 'numpy.int16'>: min=-32768, max=32767
<class 'numpy.int32'>: min=-2147483648, max=2147483647
<class 'numpy.int64'>: min=-9223372036854775808, max=9223372036854775807
<class 'numpy.float16'>: min=-65504.0, max=65504.0
<class 'numpy.float32'>: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
<class 'numpy.float64'>: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [87]:
np.set_printoptions(threshold=float("inf")) # снять ограничения
a = np.zeros((20,20))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [93]:
a = np.arange(10)
print(a)
b = np.random.uniform(low=0,high=10) #случайное значение равномерного распределения на интервале
print(b)
index = (np.abs(a-b)).argmin()
print(a[index])

[0 1 2 3 4 5 6 7 8 9]
3.1718446218904472
3


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [95]:
a = np.zeros(10, [ ('position', [ ('x', float),('y', float)]),('color',[ ('r', float),('g', float),('b', float)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [96]:
a = np.random.random((100,2))
X,Y = np.atleast_2d(a[:,0], a[:,1])
r = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(r)

[[0.         0.55832248 0.57436006 0.29231206 0.66754442 0.04993808
  0.82763328 0.81919765 0.872055   0.71350189 0.65081258 0.21378873
  0.83757536 0.10147607 0.44318742 0.50038859 0.24489242 0.6175929
  0.8768061  0.57889673 0.18280026 0.49523313 0.68693313 0.3329316
  0.27926261 0.67576292 0.11176036 0.12365633 0.88091633 0.26421824
  0.53836413 0.63294123 0.53101638 0.82649289 0.46194269 0.26589852
  0.58016208 0.23571197 0.23601455 0.67138923 0.5867662  0.10703567
  0.72118623 0.68528395 0.8690268  0.49849325 0.39106853 0.9426704
  0.61438465 0.25864794 0.37226329 0.68477175 0.66509871 0.43776614
  0.70425999 0.31093377 0.75593055 0.57669349 0.14247927 0.19277191
  0.11179069 0.28987269 0.41475851 0.0703312  0.12532533 0.75226867
  0.32629856 0.16790529 0.30418706 0.12372649 0.73987546 0.66340075
  0.21386116 0.3359126  0.83001094 0.25910441 0.43543123 0.90348719
  0.80385019 0.45046274 0.47259776 0.76155444 0.88910659 0.3964488
  0.49320362 0.98517133 0.73007944 0.22493988 0.6141

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [99]:
a = np.zeros(10, dtype=np.float32)
print(a)
a = a.astype(np.int32, copy=False)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [107]:
#я не поняла, но вроде надо так
from io import StringIO  # импортируем бибилиотеку для созрдания строкового файла
# создадим строку эмулирущую текстовый файл из задания
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  A, 7, 8  #вторая строка с коментарием и запятыми , , , , которые являются разделителями

                 ,  , 9,10,11
''') 

# теперь преобразуем файл с помощью .genfromtxt
Z = np.genfromtxt(s, filling_values= 100, delimiter=",", comments="#", dtype=np.int8)
print(Z)

[[  1   2   3   4   5]
 [  6 100 100   7   8]
 [100 100   9  10  11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [108]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [110]:
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
S = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
print(np.exp(-((S-mu)**2 / (2.0 * sigma**2))))

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [116]:
a = np.zeros((5,5))
k = 4
np.put(a, np.random.choice(range(5*5), k, replace=False), 1)
print(a)

[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [121]:
a = np.arange(10).reshape(2, 5) #чтобы проверить правильность программы создадим 2х5
print(a)
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [123]:
a = np.random.randint(0, 10, (4, 4))
print(a)
print(a[a[:, 1].argsort(), ])

[[5 1 1 3]
 [1 0 2 0]
 [4 7 0 8]
 [2 9 6 8]]
[[1 0 2 0]
 [5 1 1 3]
 [4 7 0 8]
 [2 9 6 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [124]:
a = np.random.randint(0,2,(3,10))
print(a)
print((~a.any(axis=0)).any())

[[1 0 1 1 1 0 1 1 0 0]
 [1 0 0 0 0 0 1 0 1 0]
 [0 1 1 1 0 0 0 0 0 0]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [129]:
#не поняла, чем отличается от номера 50
a = np.arange(10)
print(a)
b = np.random.uniform(low=0,high=10) #случайное значение равномерного распределения на интервале
print(b)
index = (np.abs(a-b)).argmin()
print(a[index])

[0 1 2 3 4 5 6 7 8 9]
4.764565224702132
5


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [130]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
#не поняла

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [132]:
a = np.ones(10)
print(a)
b = np.random.randint(1,9,20)
print(b)
a += np.bincount(b, minlength=len(a))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2 4 2 1 3 1 8 7 4 1 2 6 1 6 7 8 4 4 8 6]
[1. 5. 4. 2. 5. 1. 4. 3. 4. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [134]:
X = [1,2,3,4,5,6]
a = [1,3,9,3,4,1]
F = np.bincount(a,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [135]:
w,h = 16, 16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [136]:
a = np.random.randint(0,10,(3,4,3,4))
print(a.sum(axis=(-2,-1)))

[[37 38 66 46]
 [58 75 53 44]
 [55 46 44 56]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [138]:
a = np.random.uniform(0,1,100)
b = np.random.randint(0,10,100)
s = np.bincount(b, weights=a)
c = np.bincount(b)
m = s / c
print(m)

[0.5772404  0.48827527 0.48459067 0.48960977 0.51459128 0.59758845
 0.53956006 0.50461166 0.62142189 0.6036045 ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [140]:
a = np.random.randint(0,2,(4,4))
print(a)
b = np.random.randint(0,2,(4,4))
print(b)
i = np.diag(np.dot(a, b))
print(i)

[[1 0 1 0]
 [1 0 0 1]
 [0 0 1 0]
 [0 1 0 1]]
[[0 1 0 0]
 [0 0 1 1]
 [0 1 1 0]
 [1 1 1 0]]
[0 2 1 1]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [143]:
a = np.array([1,2,3,4,5])
print(a)
len_b = len(a) + (len(a)-1)*(3)  # новая длина вектора
b = np.zeros(len_b)
b[::4] = a  # вставляем в нулевой вектор значения вектора Z с шагом nz+1 
print(b)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [144]:
a = np.arange(5*5*3).reshape(5,5,3)
print(a)
b = 2*np.ones((5,5))
print(b)
print(a * b[:,:,None])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]

 [[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[  0.   2.   4.]
  [  6.   8.  10.]
  [ 12.  14.  16.]
  [ 18.  20.  22.]
  [ 24.  26.  28.]]

 [[ 30.  32.  34.]
  [ 36.  38.  40.]
  [ 42.  44.  46.]
  [ 48.  50.  52.]
  [ 54.  56.  58.]]

 [[ 60.  62.  64.]
  [ 66.  68.  70.]
  [ 72.  74.  76.]
  [ 78.  80.  82.]
  [ 84.  86.  88.]]

 [[ 90.  92.  94.]
  [ 96.  98. 100.]
  [102. 104. 106.]
  [108. 110. 112.]
  [114. 116. 118.]]

 [[120. 122. 124.]
  [126. 128. 130.]
  [132. 134. 136.]
  [138. 140. 142.]
  [144. 146. 148.]]]


#### 72. How to swap two rows of an array? (★★★)

In [146]:
a = np.arange(25).reshape((5, 5))
print(a)
a[[0, 1]] = a[[1, 0]] #свайпнем 1 и 2 строки
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [152]:
z = np.random.randint(0,100,(10,3))
a = np.roll(z.repeat(2,axis=1),-1,axis=1)
print(a[0]) #первый триплет массива
a = a.reshape(len(a)*3,2)
b = a.view( dtype=[('p0',a.dtype),('p1',a.dtype)] )
b = np.unique(b)
print(b[:3]) #вывод трех вершин

[54 79 79 65 65 54]
[(0,  8) (0, 82) (4, 54)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [156]:
c = np.sort(np.random.randint(1,10,10))
print(c)
b = np.bincount(c)
print(b)
A = np.repeat(np.arange(len(b)), repeats=b)
print(A)

[1 1 2 2 3 3 4 4 6 8]
[0 2 2 2 2 0 1 0 1]
[1 1 2 2 3 3 4 4 6 8]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [158]:
def average(arr,n):
    a = np.cumsum(arr, dtype=float)
    a[n:] = a[n:] - a[:-n]
    return a[n-1:]/n
b = np.arange(20)
print(average(b,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [159]:
from numpy.lib import stride_tricks
def sdvig(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = sdvig(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [161]:
a = np.random.randint(0,2,100)
np.logical_not(a, out=a)
a = np.random.uniform(-1.0,1.0,100)
print(np.negative(a, out=a))

[ 0.5609889   0.25842355 -0.80890097 -0.54107455 -0.4102033  -0.71903333
 -0.29607843  0.01938525 -0.66896083  0.30612102  0.36940757  0.73453873
  0.08518525  0.65982189 -0.31278209  0.63554072 -0.22723856 -0.92863179
  0.796617    0.80856913 -0.68013228 -0.42001293  0.22379824 -0.50075133
  0.07691202 -0.58374854 -0.24393487 -0.24830259  0.47334001 -0.31931523
 -0.88437107  0.13539024 -0.03468553  0.48504602 -0.03707229  0.39961753
  0.82995562 -0.44613099  0.20131713 -0.06770589 -0.64140231 -0.7005603
  0.17065797 -0.41272227  0.49044709  0.66074851 -0.65570874 -0.94975712
  0.6697263  -0.09208427  0.66584341 -0.4012497   0.82872317  0.8917328
  0.36083977  0.43587448  0.94648078  0.74014913  0.96482293  0.89934915
 -0.40213953 -0.93636915 -0.97921498 -0.02341085  0.64864507 -0.61021827
 -0.11790438  0.73556053 -0.53642671 -0.5050065  -0.1931282  -0.98736145
  0.94628461 -0.43066339  0.9326337   0.21835765 -0.0322539  -0.18229179
  0.27787948  0.70018223  0.83386737 -0.15446449  0.4

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [165]:
def distance(dP0, dP1, dpoint, w=True): #функция рассчитывает расстояния от точки и линий
    Len = dP1 - dP0  #расстояние между точками
    L2 = (Len**2).sum(axis=1)
    U = -((dP0[:,0]-dpoint[...,0])*Len[:,0] + (dP0[:,1]-dpoint[...,1])*Len[:,1]) / L2
    U = U.reshape(len(U),1)
    perpendicular = dP0 + U*Len
    D = perpendicular - dpoint
    if w:
        return np.sqrt((D**2).sum(axis=1)),perpendicular
    else:
        return np.sqrt((D**2).sum(axis=1))
P0 = np.random.randint(0,10,(3,2))
P1 = np.random.randint(0,10,(3,2))
p  = np.random.randint(0,10,( 1,2))
print(p)
a, Per_P = distance(P0,P1,p)
print(a)

[[5 8]]
[7.07106781 1.13137085 4.94974747]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [175]:
# воспользуемся функцией distance_point_to_lines из задачи 78
P0 = np.random.randint(0, 10, (3,2))
P1 = np.random.randint(0,10,(3,2))
p = np.random.randint(0, 10, (3,2)) #координаты точек
print(p)
print(np.array([distance(P0,P1,p_i, w=False) for p_i in p]))

[[4 8]
 [4 5]
 [9 0]]
[[4.91934955 1.41421356 7.        ]
 [3.57770876 0.70710678 4.        ]
 [3.13049517 0.70710678 1.        ]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [177]:
a = np.arange(1, 15, dtype=np.uint32)
print(a)
b = stride_tricks.as_strided(a, (11,4), (4,4))
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [179]:
a = np.random.randint(2,size=(5,5))
print(a)
r = np.linalg.matrix_rank(a, tol=1e-10)
print(r)

[[1 1 1 0 1]
 [0 0 0 0 1]
 [1 1 0 1 1]
 [0 1 1 1 1]
 [0 1 0 0 0]]
5


#### 83. How to find the most frequent value in an array?

In [181]:
a = np.random.randint(10,size=(10,10))
print(a)
z = np.bincount(a.flatten()).argmax()
print(z)

[[8 0 2 1 8 4 1 5 5 9]
 [0 5 2 2 1 8 7 4 8 1]
 [1 4 8 7 5 3 0 3 0 3]
 [5 6 6 4 4 1 0 9 3 2]
 [7 1 4 1 5 9 7 7 3 6]
 [3 6 9 9 7 3 2 6 6 2]
 [5 1 8 5 2 8 4 5 3 8]
 [8 9 9 1 3 1 9 5 8 7]
 [5 5 7 0 2 3 0 0 9 4]
 [9 4 9 8 4 4 0 1 7 7]]
1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [184]:
a = np.random.randint(0,5,(10,10))
print(a)
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, 3, 3), strides=Z.strides + Z.strides)
print(C)

[[3 0 0 3 3 2 1 1 4 1]
 [1 3 1 4 4 4 0 0 1 1]
 [4 2 3 1 0 1 3 4 1 3]
 [3 2 0 1 0 2 3 3 4 0]
 [1 2 2 2 2 4 1 1 3 0]
 [1 0 4 4 4 0 0 0 4 0]
 [1 2 0 3 1 1 0 1 3 3]
 [3 4 3 0 1 0 3 4 1 1]
 [4 2 3 2 0 3 2 1 2 4]
 [0 3 3 2 4 0 4 3 3 4]]
[[[[0 1 2]
   [1 2 3]
   [2 3 4]]]


 [[[1 2 3]
   [2 3 4]
   [3 4 5]]]


 [[[2 3 4]
   [3 4 5]
   [4 5 6]]]


 [[[3 4 5]
   [4 5 6]
   [5 6 7]]]


 [[[4 5 6]
   [5 6 7]
   [6 7 8]]]


 [[[5 6 7]
   [6 7 8]
   [7 8 9]]]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [185]:
p, n = 5, 10
a = np.ones((p,n,n))
b = np.ones((p,n,1))
K = np.tensordot(a, b, axes=[[0, 2], [0, 1]])
print(*K)

[50.] [50.] [50.] [50.] [50.] [50.] [50.] [50.] [50.] [50.]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [187]:
size_block = 4  # размер блока для разбиения исходной матрицы
N = 17  # размер исходной матрицы

# создадим матрицу специальным образом, чтобы убедиться в правильности работы нашего решения
# матрица будет состоять из блоков с единицами в виде русской буквы С и нулями внутри
# таким образом легко проверить начало и окончание блока и расчитать сумму его элементов для самопроверки
a = np.ones((4,4))
a[1:3,1:] = 0
A = np.tile(A=a, reps=(16 // 4,16 // 4))

if N % 4 != 0:  # в случае если размер исходной матрицы не делится без остатка на размер блока, заполняем единицами
    temp_arr = np.ones((16,16))
    temp_arr[:16 - (16 % 4),:16- (16 % 4)]= A
    Z = temp_arr

print(A)

S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], size_block), axis=0),
                                       np.arange(0, Z.shape[1], size_block), axis=1)
print(S)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [189]:
def game_life(a):
    c = (a[0:-2,0:-2] + a[0:-2,1:-1] + a[0:-2,2:] +a[1:-1,0:-2]+ a[1:-1,2:] +a[2:  ,0:-2] + a[2:  ,1:-1] + a[2:  ,2:])
    birth = (c==3) & (a[1:-1,1:-1]==0)
    survive = ((c==2) | (c==3)) & (a[1:-1,1:-1]==1)
    a[...] = 0
    a[1:-1,1:-1][birth | survive] = 1
    return a
a = np.zeros((5,5))
a[2,1:4] = 1  # Blinker
print(a)

for i in range(1,3):
    a = game_life(a)
    print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 89. How to get the n largest values of an array (★★★)

In [192]:
a = np.arange(10000)
np.random.shuffle(a)
# Fast
print(a[np.argpartition(-a, 5)[:5]])

[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [200]:
a = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
b = np.core.records.fromarrays(a.T,names='col1, col2, col3',formats = 'S8, f8, i8') #Создает массив записей из (плоского) списка массивов
print(b)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [203]:
a = np.random.random(10)
print(a)
print((a*a*a)[:5]) #первый метод
print(np.power(a,3)[:5]) #второй метод
print(np.einsum('i,i,i->i', a, a, a)[:5]) #третий метод

[0.65230231 0.71742944 0.06844738 0.52887126 0.35565862 0.18407181
 0.53756017 0.42969957 0.00282389 0.49363587]
[2.77553530e-01 3.69264522e-01 3.20678930e-04 1.47927838e-01
 4.49883465e-02]
[2.77553530e-01 3.69264522e-01 3.20678930e-04 1.47927838e-01
 4.49883465e-02]
[2.77553530e-01 3.69264522e-01 3.20678930e-04 1.47927838e-01
 4.49883465e-02]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [204]:
A = np.random.randint(0,5,(8,3))
print(A)
B = np.random.randint(0,5,(2,2))
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
i = np.where(C.any((3,1)).all(1))[0]
print(i)

[[1 4 1]
 [4 2 2]
 [3 2 1]
 [4 1 1]
 [2 3 0]
 [4 0 1]
 [0 3 1]
 [0 1 2]]
[[3 2]
 [1 1]]
[2 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [205]:
a = np.random.randint(0,3,(10,3))
print(a)
b = a[a.max(axis=1) != a.min(axis=1),:]
print(b)

[[2 1 2]
 [0 2 1]
 [2 1 0]
 [1 2 2]
 [1 0 1]
 [2 2 0]
 [2 2 2]
 [2 0 2]
 [1 1 0]
 [1 2 0]]
[[2 1 2]
 [0 2 1]
 [2 1 0]
 [1 2 2]
 [1 0 1]
 [2 2 0]
 [2 0 2]
 [1 1 0]
 [1 2 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [206]:
a = np.array([0,1,2,3,15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(a[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [207]:
a = np.random.randint(0,2,(10,3))
print(a)
b = np.ascontiguousarray(a).view(np.dtype((np.void, a.dtype.itemsize * a.shape[1])))
_, i = np.unique(b, return_index=True)
print(a[i])

[[0 0 0]
 [1 1 0]
 [1 1 0]
 [0 0 1]
 [0 0 0]
 [1 0 1]
 [0 0 0]
 [0 0 0]
 [1 0 1]
 [1 1 0]]
[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [213]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print(np.einsum('i->', A))
print(np.einsum('i,i->i', A, B))# A * B
print(np.einsum('i,i', A, B))#inner(A, B)
print(np.einsum('i,j->ij', A, B))#outer(A, B)

5.440392448922884
[0.46199059 0.0196265  0.20260653 0.11943867 0.72658655 0.4629998
 0.0012842  0.16429669 0.00228655 0.18079315]
2.3419092453317365
[[4.61990592e-01 9.69764650e-03 2.79011512e-01 6.32878492e-02
  4.67113369e-01 2.76491802e-01 6.12695554e-03 1.30330508e-01
  7.00700855e-02 2.22692276e-01]
 [9.34995871e-01 1.96265024e-02 5.64675161e-01 1.28084595e-01
  9.45363562e-01 5.59575666e-01 1.23999887e-02 2.63768329e-01
  1.41810768e-01 4.50693936e-01]
 [3.35478317e-01 7.04202679e-03 2.02606534e-01 4.59569989e-02
  3.39198264e-01 2.00776825e-01 4.44913981e-03 9.46405838e-02
  5.08819763e-02 1.61709851e-01]
 [8.71882119e-01 1.83016813e-02 5.26558663e-01 1.19438675e-01
  8.81549973e-01 5.21803393e-01 1.15629692e-02 2.45963535e-01
  1.32238309e-01 4.20271358e-01]
 [7.18618166e-01 1.50845170e-02 4.33997455e-01 9.84431262e-02
  7.26586555e-01 4.30078091e-01 9.53037060e-03 2.02726791e-01
  1.08992774e-01 3.46393882e-01]
 [7.73627095e-01 1.62392097e-02 4.67219180e-01 1.05978771e-01
  7.

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)