# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number. %run initialise.py


In [2]:
NICKNAME = "skkali"

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/79833/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/79833/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/79833/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/79833/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/79833/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/79833/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/79833/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/79833/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
print(np.zeros(10)) #создает массив заполненный нулями

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
print(np.size(np.arange(10))) #число элементов в массиве
print(np.arange(10).size * np.arange(10).itemsize) #Размер памяти занимаемый вектором в байтах

10
40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
a = np.zeros(10) #создаем массив заполненный нулями
a[4] = 1 #меняем пятый элемент на единицу
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
print(np.arange(10,50)[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
#способ из дз с numpy
def matrix(): 
    m = np.arange(9).reshape(3,3)
    return m
matrix()
#а можно так
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
print(np.nonzero(np.array([1,2,0,0,4,0]))) #Возвращает индексы элементов, которые не равны нулю

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
print(np.random.randint(low=0 , high= 3,size=(3,3,3))) #Возвращает числа в заданном интервале
print(np.random.random((3,3,3))) #Возвращает числа в интервале от 0 до 1

[[[2 2 0]
  [0 1 0]
  [1 0 0]]

 [[0 2 0]
  [2 2 1]
  [1 1 1]]

 [[2 0 0]
  [2 0 1]
  [0 1 2]]]
[[[0.06764684 0.86336914 0.53871248]
  [0.57641046 0.83721568 0.44467975]
  [0.79039013 0.63536088 0.17415473]]

 [[0.42667748 0.28993826 0.80461849]
  [0.32771884 0.46814763 0.75406535]
  [0.3834865  0.92025481 0.88155926]]

 [[0.82840552 0.56416975 0.94570264]
  [0.29416794 0.58097013 0.85630522]
  [0.36545984 0.21505238 0.52374505]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
print(np.random.random((10,10)))
print("Максимум: ", np.random.random((10,10)).max())
print('Минимум: ', np.random.random((10,10)).min())

[[0.73191302 0.29056196 0.27484343 0.91607298 0.89690719 0.65370866
  0.81476757 0.02802719 0.43437749 0.86962928]
 [0.32848847 0.05666129 0.52568604 0.0696494  0.23341088 0.68790481
  0.18857368 0.69212986 0.3597635  0.385817  ]
 [0.07281373 0.43222754 0.49382093 0.07731627 0.67357841 0.66022118
  0.54247304 0.71991391 0.86919745 0.82762307]
 [0.72397659 0.09629854 0.1338736  0.67437802 0.90877256 0.02629287
  0.25823931 0.45047275 0.6751413  0.34201083]
 [0.10106401 0.80074281 0.85308364 0.31714786 0.67756155 0.02868939
  0.12092606 0.60144096 0.22364578 0.16503547]
 [0.27516936 0.51895154 0.49093777 0.60277864 0.23459954 0.31754153
  0.75892815 0.76868253 0.40083943 0.70329384]
 [0.12052374 0.35527915 0.23402281 0.57650522 0.67160162 0.29173061
  0.29482238 0.33367301 0.20282581 0.21161382]
 [0.95014333 0.19448    0.2438888  0.64778062 0.43267681 0.32546673
  0.93069423 0.51411018 0.47157109 0.37583552]
 [0.12259644 0.83764849 0.77668574 0.54043773 0.42864267 0.65531248
  0.63029048

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
print(np.random.random(30))
print(np.random.random(30).mean()) #Возвращает среднее значение

[0.34986176 0.38817612 0.31147562 0.49023134 0.84313467 0.26176992
 0.34376998 0.6627274  0.39510705 0.5208173  0.36590804 0.5462404
 0.62357819 0.31305072 0.48935368 0.06093971 0.97189488 0.04233049
 0.30446994 0.86716109 0.36496392 0.84571613 0.10697409 0.10403183
 0.88955357 0.91147514 0.8773694  0.07070945 0.40400697 0.73811087]
0.5816192774189558


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
a = np.ones((10,10))
a[1:-1, 1:-1] = 0 #Меняем внутренние значения на 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
a = np.ones((5,5)) #для примера возьмем массив 5х5
a = np.pad(a, pad_width=1, mode='constant', constant_values=0) #Заполняет края массива нужным количеством нужных объектов
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
print(np.diag(np.arange(1,5),k=-1)) #создаем массив нужный на диагональ, затем распределяем его, K-шаг смещение по диагонали

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
#способ из дз с numpy
def checkerboard(w, b):
    m = np.tile(np.array([[0,1],[1,0]]), (4,4))
    return m
print(checkerboard(1, 0))
#а можно так
a = np.zeros((8,8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
#т.к. счет начинается с 0 сотый элемент -> 99
print(np.unravel_index(99, (6,7,8))) #Преобразуем плоский индекс вектора или массив плоских индексов в кортеж массивов координат

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
#опять же можно сделать как в дз с numpy
def checkerboard(w, b):
    m = np.tile(np.array([[0,1],[1,0]]), (4,4))
    return m
print(checkerboard(1, 0))
#а можно так
a = np.array([[0,1], [1,0]]) #создаем одну ячейку
a = np.tile(a, (4,4)) #заполняем созданными ячейками всё поле
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
a = (np.random.random((5,5)) - np.random.random((5,5)).min()) / (np.random.random((5,5)).max() - np.random.random((5,5)).min())
print(a)

[[ 0.85842515  0.23997168  0.03160095  0.62011247  0.87096324]
 [ 1.03497927  0.06627261 -0.00901798  0.42217679  0.61614699]
 [ 0.63397263  0.96143987  0.33907972  0.89350523  0.24673359]
 [ 0.51417888  0.97257815  0.48612993  0.43864219  0.01105585]
 [ 0.08180352  0.33964076  0.76716544  0.19127492  0.70561092]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
print(np.dtype([('r', np.ubyte),('g', np.ubyte),('b', np.ubyte),('a', np.ubyte)]))

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
print(np.matmul(np.random.random((5,3)),np.random.random((3,2)))) #матричное произведение двух массивов

[[1.2589243  0.96059988]
 [0.52695529 0.61901775]
 [0.79490443 1.37078485]
 [0.86008915 1.04247702]
 [0.44940643 0.67953408]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
a = np.arange(11)
a[(3<a) & (a <8)] *= -1
print(a)
#можно по старинке через цикл
a = np.arange(11)
for i in range (len(a)):
    if a[i] > 3 and a[i] < 8:
        a[i] = - a[i]
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
Z=np.arange(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
try:
    print(Z<Z>Z) # при обычном запуске дает ошибку
except Exception as e:
    print('Z<Z>Z так нельзя - бан')

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Z<Z>Z так нельзя - бан


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\79833\AppData\Local\Temp\ipykernel_22176\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\79833\AppData\Local\Temp\ipykernel_22176\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [32]:
a = np.random.uniform(-10, +10, 10)
print(a)
print(np.copysign(np.ceil(np.abs(a)), a))

[ 5.65985112 -8.36172343  6.45790928 -7.31948223  2.34273074  5.36437112
  9.37921939  4.73652469 -7.24509639  2.81430033]
[ 6. -9.  7. -8.  3.  6. 10.  5. -8.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [34]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(a1)
print(a2)
print(np.intersect1d(a1,a2))

[0 0 0 5 9 9 8 2 5 5]
[8 4 9 6 9 4 5 3 2 5]
[2 5 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [35]:
defaults = np.seterr(all = 'ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [36]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [39]:
s = np.datetime64('today')
y = np.datetime64('today') - np.timedelta64(1)
t = np.datetime64('today') + np.timedelta64(1)
print('Вчера: ',y)
print('Сегодня: ',s)
print('Завтра ',t)

Вчера:  2022-12-19
Сегодня:  2022-12-20
Завтра  2022-12-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [40]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [47]:
#чтобы оценить результат возьмем такие массивы
A = np.ones(5) * 1 
B = np.ones(5) * 2
print(A)
print(B)
np.add(A,B, out=B)
np.divide(A,2, out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)
print(A)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
[-1.5 -1.5 -1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [50]:
a = np.random.uniform(1,10,10)
print(a - a%1) #через %
print(np.floor(a)) #через floor
print(np.ceil(a)-1) #через ceil
print(a.astype(int)) #через astype
print(np.trunc(a)) #через trunc

[8. 4. 7. 6. 6. 4. 1. 6. 2. 6.]
[8. 4. 7. 6. 6. 4. 1. 6. 2. 6.]
[8. 4. 7. 6. 6. 4. 1. 6. 2. 6.]
[8 4 7 6 6 4 1 6 2 6]
[8. 4. 7. 6. 6. 4. 1. 6. 2. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [51]:
a = np.zeros((5,5)) 
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [53]:
def generator():
    for x in range(10):
        yield x
print(np.fromiter(generator(), dtype=float, count=-1))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [55]:
print(np.linspace(0,1,11,endpoint=False)[1:]) #Возвращает равномерно распределенные числа в интервале
#endpoint=False конечная точка интервала может быть исключена

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [57]:
print(np.sort(np.random.random(10)))

[0.0491199  0.14041643 0.26345926 0.30628735 0.48868634 0.53724664
 0.61261606 0.72179131 0.8256931  0.8800442 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [58]:
print(np.add.reduce(np.arange(10)))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [60]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(a)
print(b)
print(np.allclose(a,b))
print(np.array_equal(a,b))

[7 4 6 3 6 1 8 1 8 9]
[1 1 9 4 2 1 6 2 0 5]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)