Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your github nickname below:

In [ ]:
NICKNAME = "skkali"

---

# Задачи по NumPy

In [2]:
import numpy as np
import matplotlib.pyplot as plt

1. Напишите функцию, возвращающую нулевой вектор длины 10, у которого пятый элемент - единица.

*Вектор - numpy массив с shape = (n,)*

In [3]:
def null_vec():
    # YOUR CODE HERE
    a = np.zeros(10)
    a[4] = 1
    #raise NotImplementedError()
    return a
print(null_vec())

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2.Верните перевернутый вектор.

Пример: [1, 2, 3]->[3,2,1]

In [4]:
def reverse_vec(v):
    # YOUR CODE HERE
    v_rev = v[::-1]
    #raise NotImplementedError()
    return v_rev
print(reverse_vec(np.arange(3)))

[2 1 0]


3.Создайте матрицу 3x3, в которой величины будут идти по порядку от 0 до 8: 

\begin{equation*} 
\begin{pmatrix}
0 & 1 & 2 \\
3 & 4 & 5 \\
6 & 7 & 8 
\end{pmatrix}
\end{equation*}

In [5]:
def matrix():
    # YOUR CODE HERE
    m = np.arange(9).reshape(3,3)
    #raise NotImplementedError()
    return m
matrix()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Постройте матрицу размером 8х8 по принципу шахматной доски.

In [6]:
def checkerboard(w, b):
    """Создает матрицу по принципу шахматной доски.
    Parameters
    ----------
    w: Символ, обозначающий белую клетку
    b: Символ, обозначающий черную клетку
    
    Returns
    -------
    m: Матрица 8х8.
    """
    # YOUR CODE HERE
    m = np.tile(np.array([[0,1],[1,0]]), (4,4))
    #raise NotImplementedError()
    return m
print(checkerboard(1, 0))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


5. Напишите функцию, которая переводит декартовы координаты в полярные.

In [7]:
def cartesian_to_polar(c):
    A = np.arange(0,64,1)
    m = A.reshape(8,8)
    for i in range(8):
        for j in range(8):
            if (i + j) % 2 == 0:
                m[i][j] = w
            else:
                m[i][j] = b
    return m

6. Улитка Пасскаля -- плоская кривая, задаваемая уравнением в полярных координатах: $𝑟=𝑎+cos𝜙.$ 

Напишите функцию, определяющую координаты точек такой кривой.

(Подсказка: np.linspace создает одномерный массив из указанного количества элементов, значения которых равномерно распределенны внутри заданного интервала.)

In [17]:
import numpy as np
from math import cos,sin
from matplotlib import pyplot as plt
def make_curve(n, a):
    mass = np.linspace(1, 9, n)
    xy = []
    for o in mass:
        r = a + cos(o)
        x = r*cos(o)
        y = r*sin(o)
        xy.append((x,y))
    return xy
N = 50
A = 0.7
m = make_curve(N, A)
x,y=[],[]
for i in m:
    x.append(i[0])
    y.append(i[1])
plt.plot(x,y)
plt.title("улитка")
plt.ylabel('Y axis')
plt.xlabel('X axis')
plt.show()
#это то, что я строила в прошлый раз, но из-за разбиения следующей строкой, оно не работало, а так работает!

In [12]:
N = 50
A = 1
m = make_curve(N, A)

Постройте ее на плоскости xy для разных значений a.

In [20]:
def make_curve(n, a):
    phi = np.linspace(0, 2*np.pi, n)
    p = [[a+np.cos(i), i] for i in phi]
    xy = np.array([[r * np.cos(phi), r * np.sin(phi)] for r, phi in p])
    return xy
N = 50
A = 1
m = make_curve(N, A)
for a in range(1, 5):
    color = [str(a / 255.)]
    M = make_curve(N, a)
    plt.plot(M[:,0],M[:,1], color)
plt.show()
#другой вариант построения